return {
    pickup = {
        "I found {user}'s card and simply took it with me. Nobody got hurt. Nice.",
        "This is {user}'s card. The spirit was friendly, so I was friendly too.",
        "This one is from {user}. No violence required. What a pleasant surprise.",
        "{user} joined the collection willingly. Suspiciously reasonable behavior.",
        "This is {user}'s card. They surrendered before chat could start a prediction.",
        "{user}'s card acquired. The !yes voters may begin acting smug now.",
        "{user}'s card acquired peacefully. Bigbrainers will claim they knew this would happen.",
        "{user} came quietly. The tinybrainers who voted !no are devastated.",
        "This card belongs to {user}. No punches, no explosions, barely even content.",
        "{user} gave up the card without resistance. Chat has demanded a refund.",
        "I collected {user}. No Falcon Punch was needed. Clearly not a weeb.",
        "{user} was cooperative, polite, and suspiciously free of uwu noises.",
        "This is {user}'s card. Zero uguu detected. The spirit may be innocent.",
        "{user} behaved normally for several seconds and even gave me a quack. Approved.",
        "{user}'s card entered the book peacefully. No weeb behavior detected so far.",
        "{user} handed over the card. No uwu, no uguu, just a respectable quack.",
        "I found {user}. They did not appear to be a weeb, so mercy was granted.",
        "{user} survived the encounter. This is what we call premium Sweatling treatment.",
        "{user} has been safely archived. They quacked on arrival, so I trust them.",
        "This is {user}'s card. A fine Twitch Sweatling: no weeb noises, excellent quack.",
        "{user} entered the book voluntarily. They are now legally part of the run.",
        "{user}'s card secured. Another Sweatling for my increasingly concerning collection.",
        "{user} has been collected. The Sweatling inventory grows stronger.",
        "{user}'s card is mine now. They seemed happy about it, which is slightly worrying.",
        "{user} was picked up gently and placed in the book like a particularly chatty collectible.",
        "{user} joined the run peacefully. Please feed the Sweatling responsibly.",
        "{user}'s card acquired. The Sweatling has been classified as mostly harmless.",
        "{user} was collected without incident. Rare footage of Twitch chat behaving.",
        "This is {user}'s card. They were probably just here to talk about brisket.",
        "{user} surrendered immediately after hearing there might be brisket later.",
        "{user}'s card acquired. Vegetables were not involved, so morale remains high.",
        "{user} joined willingly. They understand that vegetables are garnish, not food.",
        "{user}'s card is safe. Payment was accepted in the form of imaginary brisket.",
        "{user} has been collected. Brisket diplomacy remains undefeated.",
        "{user} entered the book peacefully after a lengthy discussion about food.",
        "This is {user}'s card. Somehow the conversation became about brisket again.",
        "{user} was collected before I could explain smoked meat for another forty minutes.",
        "{user}'s card acquired. Texas has approved this transaction.",
        "{user} joined the collection peacefully. Yeehaw levels remain within safe limits.",
        "This is {user}'s card. The spirit asked when Dunkbot 2.0 releases. Nobody answered.",
        "{user} trusted the Dunkbot 2.0 roadmap. Adorable.",
        "{user}'s card has been secured. Dunkbot 2.0 remains completely, definitely real.",
        "{user} joined peacefully while waiting for Dunkbot 2.0. They may be here a while.",
        "This is {user}'s card. Someone whispered NT Sadge nearby. I chose to ignore the propaganda.",
        "{user} tried to bring up Noita Together. I collected the card before the discussion got worse.",
        "{user}'s card joined the book. They promised not to ask for NT back. Sensible choice.",
        "{user} came peacefully and did not mention Noita Together once. Excellent behavior.",
        "{user}'s card is safe. DEMBOYS approval has been granted.",
        "{user} joined peacefully while openly supporting the Cowboys. Clearly one of the good ones.",
        "This is {user}'s card. A Cowboys logo was spotted. I immediately knew this Sweatling had taste.",
        "{user} was collected peacefully. No DEMBOYS slander detected. Good.",
        "{user}'s card acquired. They asked if Dunk is bald. Dangerous conversation starter.",
        "{user} joined the book peacefully after complimenting my luxurious and very real hair.",
        "This is {user}'s card. No bald jokes were made during collection. Officially.",
        "{user} was safely collected. Chat insists the shiny head reflection was unrelated.",
        "{user}'s card acquired. The prediction market is already rewriting history.",
        "{user} joined peacefully. The !yes bigbrainers understood the assignment. !no remains confused.",
        "This is {user}'s card. The !yes bigbrainers were correct, naturally. Tinybrainers may cope.",
        "{user} came willingly. The bigbrainers are nodding as if this was all according to plan.",
        "{user}'s card is in the book. Tinybrainers are currently filing an appeal.",
        "{user} was collected peacefully. Twitch chat immediately made it weird.",
        "This is {user}'s card. The spirit gave me a quack instead of an uwu. Immediate approval.",
        "{user} has been archived. Their browser history remains sealed for everyone's safety.",
        "{user}'s card acquired. The spirit winked. I pretended not to notice.",
    },
    kill = {
        "This is {user}'s card. I had to take care of the spirit. I swear it was a weeb.",
        "{user}'s card is mine now. The spirit made this unnecessarily difficult.",
        "This card belonged to {user}. The spirit chose violence. I finished the discussion.",
        "I recovered {user}'s card. There was an incident. The spirit will not be commenting.",
        "This is {user}'s card. I asked nicely. Things escalated.",
        "{user}'s card has been secured. Please ignore what happened to the spirit.",
        "A card from {user}. The spirit resisted. That was its final mistake.",
        "I got {user}'s card. The spirit and I had a disagreement. I won.",
        "{user} said uwu. The rest was procedure.",
        "{user} said uguu. A Falcon Punch was authorized immediately.",
        "This is {user}'s card. Weeb activity was detected and corrected.",
        "{user}'s card recovered. The anti-weeb department thanks you for your cooperation.",
        "{user} made one suspicious anime noise. I chose the punch counter.",
        "This card belonged to {user}. I heard uwu and the punch counter activated on instinct.",
        "{user}'s spirit attempted an uguu. It did not get to finish.",
        "{user}'s card is secure. The Falcon Punch was justified. Weeb threat neutralized.",
        "I found {user}. They chose uwu. I chose punch counter.",
        "{user} challenged my anti-weeb policy. The appeal was denied.",
        "This is {user}'s card. The spirit was caught being extremely anime in public.",
        "{user}'s card recovered. Weeb containment failed, so elimination was required.",
        "{user} chose violence. More importantly, they chose uwu. Fatal combination.",
        "{user}'s card is mine. The spirit had cat ears. I rest my case.",
        "This card belonged to {user}. The spirit called me senpai. It was over instantly.",
        "{user} whispered uguu. Somewhere, a Falcon Punch began charging.",
        "{user}'s card recovered after an entirely proportionate response to anime behavior.",
        "{user} was removed from the census for excessive weebing.",
        "This is {user}'s card. Their final mistake was believing the uwu would protect them.",
        "{user}'s spirit has been sent directly to the shadow realm. Very sad. Anyway.",
        "{user} resisted collection. The !yes bigbrainers correctly predicted how this would end.",
        "{user}'s card acquired. The !no tinybrainers are blaming lag.",
        "{user} fought back. The bigbrainers knew exactly how this would end.",
        "{user}'s card is safe. The prediction payout was emotionally devastating.",
        "This is {user}'s card. !yes gets paid, !no gets character development.",
        "{user} became a valuable lesson in why the !yes bigbrainers are called bigbrainers.",
        "{user}'s card recovered. Tinybrainers are typing rigged at record speed.",
        "{user} died for the content. The channel point economy thanks them.",
        "This is {user}'s card. The Sweatling union has requested an investigation.",
        "{user}'s card acquired. Another Sweatling has been converted into book lore.",
        "{user} refused to join the collection. I solved the inventory problem permanently.",
        "{user}'s spirit resisted. Collection became archaeology.",
        "This is {user}'s card. The Sweatling was not OSHA compliant.",
        "{user}'s card was recovered from the scene. Please do not ask for details.",
        "{user} is now significantly easier to store.",
        "{user}'s card acquired. The spirit has been compacted for convenience.",
        "This is {user}'s card. Brisket negotiations broke down.",
        "{user} suggested vegetables for dinner. There was no other possible outcome.",
        "{user}'s card recovered. The spirit called salad a meal. Unforgivable.",
        "{user} brought vegetables to a brisket discussion. Texas law was consulted.",
        "This is {user}'s card. The spirit disrespected brisket and paid the price.",
        "{user}'s card acquired after a heated debate about smoked meat.",
        "{user} claimed vegetables are food. The court found them guilty immediately.",
        "{user}'s spirit said brisket was overrated. Even chat went silent.",
        "{user} asked when Dunkbot 2.0 releases. I reacted normally and calmly.",
        "{user}'s card recovered. They called Dunkbot 2.0 vaporware. Bold final words.",
        "This is {user}'s card. The spirit laughed at the Dunkbot 2.0 release date.",
        "{user} said Dunkbot 2.0 is never coming. Ragebait was successful.",
        "{user}'s spirit asked to see the Dunkbot 2.0 changelog. Fatal curiosity.",
        "This is {user}'s card. They demanded NT back. Absolutely unacceptable behavior.",
        "{user} mentioned Noita Together like it was a good idea. I disagreed physically.",
        "{user}'s card recovered. They tried to campaign for NT. The campaign has ended.",
        "{user} whispered bring back NT. I heard enough.",
        "This is {user}'s card. They died still asking for Noita Together. Tragic stubbornness.",
        "{user}'s card acquired. They mocked DEMBOYS. I took that personally.",
        "{user} mocked the Cowboys. I corrected that mistake immediately.",
        "This is {user}'s card. The Cowboys slander somehow became lethal.",
        "{user} shouted anti-DEMBOYS nonsense before the incident. Poor final choice.",
        "{user}'s spirit laughed at the Cowboys logo. I stopped the slander at the source.",
        "This is {user}'s card. They called me bald. Cause of death remains mysterious.",
        "{user} asked where my hair went. Investigation closed immediately.",
        "{user}'s card recovered. The spirit claimed my hair was a scalp reflection. Slander.",
        "{user} made a bald joke. I demonstrated a surprisingly aerodynamic response.",
        "This is {user}'s card. The spirit called me bald. Completely false and extremely unwise.",
        "{user} tried to run after making a bald joke. My luxurious hair did not save them.",
        "{user}'s card acquired. Twitch chat made the entire encounter slightly inappropriate.",
        "{user} said something that would absolutely get clipped out of context.",
        "This is {user}'s card. The spirit flirted with danger and then actually met it.",
        "{user}'s final words were suspiciously suggestive. Chat behaved exactly as expected.",
        "{user}'s card recovered. The spirit asked to be handled gently. That request was not processed.",
        "{user} made it weird. I made it worse. The book gets a card.",
        "This is {user}'s card. The spirit requested a spanking. The moderation team has no statement.",
        "{user}'s card acquired. Nobody is allowed to review the VOD in slow motion.",
        "{user} said harder during combat. The rest of the encounter has been legally sealed.",
        "This is {user}'s card. Chat needs to go outside after this one.",
    }
}
