return {
    pickup = {
        "This is {user}'s card. I thankfully took it. Such a nice person.",
        "This one belongs to {user}. They handed it over without a fight. Very considerate.",
        "{user}'s card is safe in the book now. A peaceful exchange for once.",
        "I found {user}'s card and simply took it with me. Nobody got hurt. Nice.",
        "This is {user}'s card. The spirit was friendly, so I was friendly too.",
        "{user} left me this card. I accepted it politely and moved on.",
        "A card from {user}. Collected peacefully. I could get used to this.",
        "This one is from {user}. No violence required. What a pleasant surprise.",
        "{user} joined the collection willingly. Suspiciously reasonable behavior.",
        "This is {user}'s card. They surrendered before chat could start a prediction.",
        "{user}'s card acquired. The !yes voters may begin acting smug now.",
        "{user}'s card acquired peacefully. Bigbrainers will claim they knew this would happen.",
        "{user} came quietly. The tinybrainers who voted !no are devastated.",
        "This card belongs to {user}. No punches, no explosions, barely even content.",
        "{user} gave up the card without resistance. Chat has demanded a refund.",
        "I collected {user}. Not even a Falcon Punch was required. Disappointing.",
        "{user} was cooperative, polite, and suspiciously free of uwu noises.",
        "This is {user}'s card. Zero uguu detected. The spirit may be innocent.",
        "{user} behaved normally for several seconds. A new channel record.",
        "{user}'s card entered the book peacefully. Weeb status remains under investigation.",
        "{user} handed over the card. No uwu, no uguu, no crimes were committed today.",
        "I found {user}. They did not appear to be a weeb, so mercy was granted.",
        "{user}'s card was collected with no Falcon Punches.",
        "{user} survived the encounter. This is what we call premium Sweatling treatment.",
        "{user} has been safely archived. Please do not tap on the glass.",
        "This is {user}'s card. A fine specimen of the common Twitch Sweatling.",
        "{user} entered the book voluntarily. They are now legally part of the run.",
        "{user}'s card secured. Another Sweatling for my increasingly concerning collection.",
        "{user} has been collected. The Sweatling inventory grows stronger.",
        "{user}'s card is mine now. They seemed happy about it, which is slightly worrying.",
        "{user} was picked up gently and placed in the book like a particularly chatty collectible.",
        "{user} joined the run peacefully. Please feed the Sweatling responsibly.",
        "{user}'s card acquired. The Sweatling has been classified as mostly harmless.",
        "{user} was collected without incident. Rare footage of Twitch chat behaving.",
        "This is {user}'s card. They were probably just here to talk about brisket.",
        "{user} surrendered immediately after hearing there might be brisket later.",
        "{user}'s card acquired. Vegetables were not involved, so morale remains high.",
        "{user} joined willingly. They understand that vegetables are garnish, not food.",
        "{user}'s card is safe. Payment was accepted in the form of imaginary brisket.",
        "{user} has been collected. Brisket diplomacy remains undefeated.",
        "{user} entered the book peacefully after a lengthy discussion about food.",
        "This is {user}'s card. Somehow the conversation became about brisket again.",
        "{user} was collected before I could explain smoked meat for another forty minutes.",
        "{user}'s card acquired. Texas has approved this transaction.",
        "{user} joined the collection peacefully. Yeehaw levels remain within safe limits.",
        "This is {user}'s card. The spirit asked when Dunkbot 2.0 releases. Nobody answered.",
        "{user} trusted the Dunkbot 2.0 roadmap. Adorable.",
        "{user}'s card has been secured. Dunkbot 2.0 remains completely, definitely real.",
        "{user} joined peacefully while waiting for Dunkbot 2.0. They may be here a while.",
        "This is {user}'s card. NT Sadge was whispered softly in the distance.",
        "{user} was collected while mourning Noita Together. NT Sadge.",
        "{user}'s card joined the book. They still believe NT will return someday.",
        "{user} came peacefully. The old Noita Together veterans shed a single tear.",
        "{user}'s card is safe. DEMBOYS remain under observation.",
        "{user} joined peacefully despite openly supporting the Cowboys. Brave.",
        "This is {user}'s card. A Cowboys logo was spotted. Chat immediately pointed and laughed.",
        "{user} was collected before the DEMBOYS slander could escalate.",
        "{user}'s card acquired. They asked if Dunk is bald. Dangerous conversation starter.",
        "{user} joined the book peacefully after complimenting my luxurious and very real hair.",
        "This is {user}'s card. No bald jokes were made during collection. Officially.",
        "{user} was safely collected. Chat insists the shiny head reflection was unrelated.",
        "{user}'s card acquired. The prediction market is already rewriting history.",
        "{user} joined peacefully. !yes claims skill, !no claims streamer luck.",
        "This is {user}'s card. Somehow both sides of the prediction think they won.",
        "{user} came willingly. The bigbrainers are nodding as if this was all according to plan.",
        "{user}'s card is in the book. Tinybrainers are currently filing an appeal.",
        "{user} was collected peacefully. Twitch chat immediately made it weird.",
        "This is {user}'s card. The spirit said uwu once, but we are choosing forgiveness today.",
        "{user} has been archived. Their browser history remains sealed for everyone's safety.",
        "{user}'s card acquired. The spirit winked. I pretended not to notice.",
    },
    kill = {
        "This is {user}'s card. I had to take care of the spirit. I swear it was a weeb.",
        "{user}'s card is mine now. The spirit made this unnecessarily difficult.",
        "This card belonged to {user}. The spirit chose violence. I finished the discussion.",
        "I recovered {user}'s card. There was an incident. The spirit will not be commenting.",
        "This is {user}'s card. I asked nicely. Things escalated.",
        "{user}'s card has been secured. Please ignore what happened to the spirit.",
        "A card from {user}. The spirit resisted. That was its final mistake.",
        "I got {user}'s card. The spirit and I had a disagreement. I won.",
        "{user} said uwu. The rest was procedure.",
        "{user} said uguu. A Falcon Punch was authorized immediately.",
        "This is {user}'s card. Weeb activity was detected and corrected.",
        "{user}'s card recovered. The anti-weeb department thanks you for your cooperation.",
        "{user} made one suspicious anime noise. I chose the nuclear option.",
        "This card belonged to {user}. Chat heard uwu and demanded justice.",
        "{user}'s spirit attempted an uguu. It did not get to finish.",
        "{user}'s card is secure. The Falcon Punch paperwork has been filed.",
        "I found {user}. Unfortunately, so did the punch button.",
        "{user} challenged my anti-weeb policy. The appeal was denied.",
        "This is {user}'s card. The spirit was caught being extremely anime in public.",
        "{user}'s card recovered. Weeb containment failed, so elimination was required.",
        "{user} chose violence. More importantly, they chose uwu. Fatal combination.",
        "{user}'s card is mine. The spirit had cat ears. I rest my case.",
        "This card belonged to {user}. The spirit called me senpai. It was over instantly.",
        "{user} whispered uguu. Somewhere, a Falcon Punch began charging.",
        "{user}'s card recovered after an entirely proportionate response to anime behavior.",
        "{user} was removed from the census for excessive weebing.",
        "This is {user}'s card. Their final mistake was believing the uwu would protect them.",
        "{user}'s spirit has been sent directly to the shadow realm. Very sad. Anyway.",
        "{user} resisted collection. Chat voted !yes on excessive force.",
        "{user}'s card acquired. The !no tinybrainers are blaming lag.",
        "{user} fought back. The bigbrainers knew exactly how this would end.",
        "{user}'s card is safe. The prediction payout was emotionally devastating.",
        "This is {user}'s card. !yes gets paid, !no gets character development.",
        "{user} became a valuable lesson in why you never bet against streamer luck.",
        "{user}'s card recovered. Tinybrainers are typing rigged at record speed.",
        "{user} died for the content. The channel point economy thanks them.",
        "This is {user}'s card. The Sweatling union has requested an investigation.",
        "{user}'s card acquired. Another Sweatling has been converted into book lore.",
        "{user} refused to join the collection. I solved the inventory problem permanently.",
        "{user}'s spirit resisted. Collection became archaeology.",
        "This is {user}'s card. The Sweatling was not OSHA compliant.",
        "{user}'s card was recovered from the scene. Please do not ask for details.",
        "{user} is now significantly easier to store.",
        "{user}'s card acquired. The spirit has been compacted for convenience.",
        "This is {user}'s card. Brisket negotiations broke down.",
        "{user} suggested vegetables for dinner. There was no other possible outcome.",
        "{user}'s card recovered. The spirit called salad a meal. Unforgivable.",
        "{user} brought vegetables to a brisket discussion. Texas law was consulted.",
        "This is {user}'s card. The spirit disrespected brisket and paid the price.",
        "{user}'s card acquired after a heated debate about smoked meat.",
        "{user} claimed vegetables are food. The court found them guilty immediately.",
        "{user}'s spirit said brisket was overrated. Even chat went silent.",
        "{user} asked when Dunkbot 2.0 releases. I reacted normally and calmly.",
        "{user}'s card recovered. They called Dunkbot 2.0 vaporware. Bold final words.",
        "This is {user}'s card. The spirit laughed at the Dunkbot 2.0 release date.",
        "{user} said Dunkbot 2.0 is never coming. Ragebait was successful.",
        "{user}'s spirit asked to see the Dunkbot 2.0 changelog. Fatal curiosity.",
        "This is {user}'s card. NT Sadge. Very NT Sadge.",
        "{user} mentioned Noita Together. The sadness became physical.",
        "{user}'s card recovered. Another casualty of the post-NT timeline.",
        "{user} whispered bring back NT. The run became emotional.",
        "This is {user}'s card. They died believing Noita Together would return.",
        "{user}'s card acquired. DEMBOYS tried to intervene and missed wide right.",
        "{user} defended the Cowboys. Chat pointed at the logo and laughed.",
        "This is {user}'s card. The Cowboys slander somehow became lethal.",
        "{user} shouted DEMBOYS before the incident. Respect the commitment.",
        "{user}'s spirit wore Cowboys colors. The chat emote appeared instantly.",
        "This is {user}'s card. They called me bald. Cause of death remains mysterious.",
        "{user} asked where my hair went. Investigation closed immediately.",
        "{user}'s card recovered. The spirit confused scalp reflection with a light source.",
        "{user} made a bald joke. I demonstrated a surprisingly aerodynamic response.",
        "This is {user}'s card. The spirit called him shiny. It was technically accurate and still unwise.",
        "{user} tried to run after making a bald joke. The forehead glare revealed their position.",
        "{user}'s card acquired. Twitch chat made the entire encounter slightly inappropriate.",
        "{user} said something that would absolutely get clipped out of context.",
        "This is {user}'s card. The spirit flirted with danger and then actually met it.",
        "{user}'s final words were suspiciously suggestive. Chat behaved exactly as expected.",
        "{user}'s card recovered. The spirit asked to be handled gently. That request was not processed.",
        "{user} made it weird. I made it worse. The book gets a card.",
        "This is {user}'s card. The spirit requested a spanking. The moderation team has no statement.",
        "{user}'s card acquired. Nobody is allowed to review the VOD in slow motion.",
        "{user} said harder during combat. The rest of the encounter has been legally sealed.",
        "This is {user}'s card. Chat needs to go outside after this one.",
    }
}
